### ISSUE TITLE
The overflow is not work in android scrollview when the children is a Image

### ISSUE THREAD

**Issue by mcmPan** [Tencent/Hippy#2671]
**Describe the bug**

When I set  ScrollView Style Like this, The borderRadius is not work in Android Image.
```
<ScrollView
  horizontal={true}
  style={{
      marginHorizontal: 20,
      overflow: 'hidden',
      borderTopLeftRadius: 40,
      borderTopRightRadius: 40,
    }}
  bounces={false}
    <Image source={{uri: someurl}} style={{ height: 578, width: 1000}}></Image>
</ScrollView>
```

**Expected behavior**

In iOS, The BorderRadius above the Image are hidden.
But in Android, The Image still rectangle without BorderRadius

**Screenshots**
The expected result In iOS：

<img width="414" alt="image" src="https://user-images.githubusercontent.com/17811452/202954049-f4360662-4a6a-406f-b86a-81a8c24159dc.png">

But it is Wrong In Android:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/17811452/202954210-e2618622-164a-4207-889f-71e9f89a5406.png">

**Comment by iPel** [comment]
Due to the limitations of the current implementation, ScrollView does not support rounded corners, and the rounded corners of the View component do not support hidden child elements. You can try to implement a custom component with [cardview](https://developer.android.com/jetpack/androidx/releases/cardview) to achieve your needs.
