### ISSUE TITLE
Encorage to use English on the Issues/PR

### ISSUE THREAD

**Issue by cmpeguerog** [Tencent/Hippy#287]
**Use English on comments.**
As a public project i think that a good solution is always to write the Issues/PR comments using english so there is no need to translate from Spanish/English .... to Chinese or other language to search for specific solution to problems.

**Comment by xuqingkuang** [comment]
Which language will be used is dependent on the users who are using the framework.

I agree with your opinion of "always to write the Issues/PR comments using English", the problem is most users of Hippy are Chinese so far.

We are working hard to increase Hippy's influence in the English-speaking world but as you can see it needs everyone to do better.
