### ISSUE TITLE
Please add the Docker images

### ISSUE THREAD

**Issue by XVilka** [Tencent/Hippy#33]
Please add the docker images for building and running the tests.
[React Native] has such thing, see these as an example:
- https://github.com/react-native-community/docker-android
- https://github.com/entria/docker-react-native-android
- https://dev.to/ghost/running-exporeact-native-in-docker-4hme

**Comment by xuqingkuang** [comment]
I have considering about it, first of all, I can't confirm Hippy can run in Docker because of the mechanism is different, as the second I think the feature provide by the community may be better(as you can see the react-native docker is not provided by official also).

I had created a [Hippy Contrib](https://github.com/hippy-contrib) organization, all of your internal eco-system will be open source in this organization soon. I would like to add the docker image project to the organization if someone will maintain it.
