### ISSUE TITLE
Do you have a plan to opensource the adpapted V8 engine(mttv8) on Android in the future?

### ISSUE THREAD

**Issue by krisfeng** [Tencent/Hippy#9]
Do you have a plan to opensource the adpapted V8 engine(mttv8) on Android in the future? Just checked the sourcecode, only found libmttv8.so and libmtt_shared.so.
Thanks.

**Comment by xuqingkuang** [comment]
The `libmttv8` is part of [X5 engine](https://x5.tencent.com/), but I think we can't see the X5 engine be open source in a short time. The reason is it contains a lot of private implementation that hard to open source.

But X5 is optimized for Tencent apps including Hippy. We had a test before, the same code running on X5 is better than other engines.

As everybody knows, the latest X5 is based on [Google Blink](http://www.chromium.org/blink) and licensed by BSD, so Tencent has the right to keep X5 be private.

**Comment by krisfeng** [comment]
Got you and thank you for your prompt reply.
